// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `WalletEntities`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=89.20.42.182;Database=Wallet;User Id=av_admin;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Wallets
{
    /// <summary>
    /// A class which represents the Wallets table.
    /// </summary>
	[Table("Wallets")]
	public partial class Wallet
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual decimal Sum { get; set; }
		public virtual string Description { get; set; }
	}

}
